
import { Storyboard } from '../types';

export const generatePythonSynthesisScript = (storyboard: Storyboard): string => {
  const storyboardJson = JSON.stringify(storyboard, null, 2);

  return `
"""
Historian AI: Cinematic Professional Video Synthesis Script
Generated by Historian AI Director

REQUIRED LIBRARIES:
pip install moviepy numpy requests

SYSTEM REQUIREMENT:
- ImageMagick must be installed on your system for TextClip.
"""

import json
import os
import base64
import wave
import requests
from moviepy.editor import ImageClip, AudioFileClip, TextClip, CompositeVideoClip, concatenate_videoclips, ColorClip, afx

# --- Production Configuration ---
DATA = ${storyboardJson}
OUTPUT_FILE = "final_short_video.mp4"
ASSETS_DIR = "production_assets"
os.makedirs(ASSETS_DIR, exist_ok=True)

BGM_URLS = {
    "epic": "https://cdn.pixabay.com/audio/2022/03/10/audio_afbd0a3861.mp3",
    "sad": "https://cdn.pixabay.com/audio/2022/10/25/audio_1739777f9e.mp3",
    "peaceful": "https://cdn.pixabay.com/audio/2022/01/21/audio_31308e7b51.mp3",
    "suspense": "https://cdn.pixabay.com/audio/2024/02/22/audio_95945893d5.mp3"
}

def download_bgm(style):
    url = BGM_URLS.get(style, BGM_URLS["epic"])
    path = os.path.join(ASSETS_DIR, "background_music.mp3")
    print(f"📥 Downloading BGM for style: {style}...")
    response = requests.get(url)
    with open(path, "wb") as f:
        f.write(response.content)
    return path

def save_pcm_as_wav(base64_pcm, output_path):
    pcm_data = base64.b64decode(base64_pcm)
    with wave.open(output_path, 'wb') as wav_file:
        wav_file.setnchannels(1)
        wav_file.setsampwidth(2)
        wav_file.setframerate(24000)
        wav_file.writeframes(pcm_data)

def save_image(base64_img, output_path):
    header, encoded = base64_img.split(",", 1)
    with open(output_path, "wb") as f:
        f.write(base64.b64decode(encoded))

def create_scene_clip(scene_data, index):
    print(f"  🎬 Processing Scene {index + 1}...")
    img_path = os.path.join(ASSETS_DIR, f"scene_{index}.png")
    audio_path = os.path.join(ASSETS_DIR, f"scene_{index}.wav")
    
    save_image(scene_data['imageUrl'], img_path)
    save_pcm_as_wav(scene_data['audioUrl'], audio_path)

    audio = AudioFileClip(audio_path)
    duration = audio.duration
    
    # Visual Layer (9:16)
    img_clip = (ImageClip(img_path)
                .set_duration(duration)
                .resize(height=1920)
                .on_color(size=(1080, 1920), color=(0,0,0), pos='center'))
    
    # Ken Burns Zoom (1.0 to 1.15)
    img_clip = img_clip.resize(lambda t: 1.0 + (0.15 * (t / duration)))

    # Telop Background Bar
    is_highlight = scene_data.get('telop_style') == 'highlight'
    bg_color = (180, 0, 0) if is_highlight else (0, 0, 0)
    
    txt_bg = (ColorClip(size=(1080, 260), color=bg_color)
              .set_opacity(0.7)
              .set_position(('center', 1480))
              .set_duration(duration))

    # Telop Text
    txt_clip = (TextClip(scene_data['telop'], 
                         fontsize=65, 
                         color='white', 
                         font='Arial-Bold',
                         method='caption', 
                         size=(900, 260))
                .set_position(('center', 1480))
                .set_duration(duration))

    return CompositeVideoClip([img_clip, txt_bg, txt_clip]).set_audio(audio)

def synthesize():
    print("🚀 INITIALIZING PRO-LEVEL SYNTHESIS...")
    
    # Prepare all scene clips
    clips = []
    for i, scene in enumerate(DATA['scenes']):
        if not scene.get('imageUrl') or not scene.get('audioUrl'):
            continue
        clips.append(create_scene_clip(scene, i))
    
    if not clips:
        print("❌ Error: Assets incomplete.")
        return

    # Combine scenes
    video_content = concatenate_videoclips(clips, method="compose")
    
    # Add BGM
    bgm_path = download_bgm(DATA.get('bgm_style', 'epic'))
    bgm = AudioFileClip(bgm_path).volumex(0.18).set_duration(video_content.duration).audio_fadeout(3)
    
    # Final audio mix: Narration (from video_content) + BGM
    final_audio = CompositeAudioClip([video_content.audio, bgm])
    final_video = video_content.set_audio(final_audio)

    print("🎞️ Rendering final MP4 (9:16 1080x1920)...")
    final_video.write_videofile(OUTPUT_FILE, fps=24, codec="libx264", audio_codec="aac")
    print(f"✅ PRODUCTION COMPLETE: {OUTPUT_FILE}")

if __name__ == "__main__":
    from moviepy.audio.AudioClip import CompositeAudioClip
    synthesize()
`;
};
